
package com.muhimbi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentConverterService", targetNamespace = "http://services.muhimbi.com/2009/10/06")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentConverterService {


    /**
     * 
     * @param conversionSettings
     * @param sourceFile
     * @param openOptions
     * @return
     *     returns byte[]
     * @throws DocumentConverterServiceConvertWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "Convert", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/Convert")
    @WebResult(name = "ConvertResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ConvertResponse")
    public byte[] convert(
        @WebParam(name = "sourceFile", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        byte[] sourceFile,
        @WebParam(name = "openOptions", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        OpenOptions openOptions,
        @WebParam(name = "conversionSettings", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        ConversionSettings conversionSettings)
        throws DocumentConverterServiceConvertWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param conversionSettings
     * @param sourceFile
     * @param openOptions
     * @return
     *     returns byte[]
     * @throws DocumentConverterServiceApplyWatermarkWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ApplyWatermark", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/ApplyWatermark")
    @WebResult(name = "ApplyWatermarkResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "ApplyWatermark", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ApplyWatermark")
    @ResponseWrapper(localName = "ApplyWatermarkResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ApplyWatermarkResponse")
    public byte[] applyWatermark(
        @WebParam(name = "sourceFile", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        byte[] sourceFile,
        @WebParam(name = "openOptions", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        OpenOptions openOptions,
        @WebParam(name = "conversionSettings", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        ConversionSettings conversionSettings)
        throws DocumentConverterServiceApplyWatermarkWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param conversionSettings
     * @param sourceFile
     * @param openOptions
     * @return
     *     returns byte[]
     * @throws DocumentConverterServiceApplySecurityWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ApplySecurity", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/ApplySecurity")
    @WebResult(name = "ApplySecurityResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "ApplySecurity", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ApplySecurity")
    @ResponseWrapper(localName = "ApplySecurityResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ApplySecurityResponse")
    public byte[] applySecurity(
        @WebParam(name = "sourceFile", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        byte[] sourceFile,
        @WebParam(name = "openOptions", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        OpenOptions openOptions,
        @WebParam(name = "conversionSettings", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        ConversionSettings conversionSettings)
        throws DocumentConverterServiceApplySecurityWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param conversionSettings
     * @param sourceFile
     * @param openOptions
     * @return
     *     returns byte[]
     * @throws DocumentConverterServiceProcessChangesWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessChanges", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/ProcessChanges")
    @WebResult(name = "ProcessChangesResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "ProcessChanges", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ProcessChanges")
    @ResponseWrapper(localName = "ProcessChangesResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ProcessChangesResponse")
    public byte[] processChanges(
        @WebParam(name = "sourceFile", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        byte[] sourceFile,
        @WebParam(name = "openOptions", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        OpenOptions openOptions,
        @WebParam(name = "conversionSettings", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        ConversionSettings conversionSettings)
        throws DocumentConverterServiceProcessChangesWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param options
     * @return
     *     returns com.muhimbi.ws.BatchResults
     * @throws DocumentConverterServiceProcessBatchWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ProcessBatch", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/ProcessBatch")
    @WebResult(name = "ProcessBatchResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "ProcessBatch", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ProcessBatch")
    @ResponseWrapper(localName = "ProcessBatchResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.ProcessBatchResponse")
    public BatchResults processBatch(
        @WebParam(name = "options", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        ProcessingOptions options)
        throws DocumentConverterServiceProcessBatchWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.muhimbi.ws.Configuration
     * @throws DocumentConverterServiceGetConfigurationWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetConfiguration", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/GetConfiguration")
    @WebResult(name = "GetConfigurationResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "GetConfiguration", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.GetConfiguration")
    @ResponseWrapper(localName = "GetConfigurationResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.GetConfigurationResponse")
    public Configuration getConfiguration()
        throws DocumentConverterServiceGetConfigurationWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param convertersToDiagnose
     * @return
     *     returns com.muhimbi.ws.Diagnostics
     * @throws DocumentConverterServiceGetDiagnosticsWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetDiagnostics", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/GetDiagnostics")
    @WebResult(name = "GetDiagnosticsResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "GetDiagnostics", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.GetDiagnostics")
    @ResponseWrapper(localName = "GetDiagnosticsResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.GetDiagnosticsResponse")
    public Diagnostics getDiagnostics(
        @WebParam(name = "convertersToDiagnose", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        ArrayOfDiagnosticRequestItem convertersToDiagnose)
        throws DocumentConverterServiceGetDiagnosticsWebServiceFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param statusRequest
     * @return
     *     returns com.muhimbi.ws.Status
     * @throws DocumentConverterServiceGetStatusWebServiceFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "GetStatus", action = "http://services.muhimbi.com/2009/10/06/DocumentConverterService/GetStatus")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://services.muhimbi.com/2009/10/06")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://services.muhimbi.com/2009/10/06", className = "com.muhimbi.ws.GetStatusResponse")
    public Status getStatus(
        @WebParam(name = "statusRequest", targetNamespace = "http://services.muhimbi.com/2009/10/06")
        StatusRequest statusRequest)
        throws DocumentConverterServiceGetStatusWebServiceFaultExceptionFaultFaultMessage
    ;

}
