
package com.muhimbi.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentConverterService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:41734/Muhimbi.DocumentConverter.WebService/?wsdl")
public class DocumentConverterService_Service
    extends Service
{

    private final static URL DOCUMENTCONVERTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTCONVERTERSERVICE_EXCEPTION;
    private final static QName DOCUMENTCONVERTERSERVICE_QNAME = new QName("http://tempuri.org/", "DocumentConverterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:41734/Muhimbi.DocumentConverter.WebService/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTCONVERTERSERVICE_WSDL_LOCATION = url;
        DOCUMENTCONVERTERSERVICE_EXCEPTION = e;
    }

    public DocumentConverterService_Service() {
        super(__getWsdlLocation(), DOCUMENTCONVERTERSERVICE_QNAME);
    }

    public DocumentConverterService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTCONVERTERSERVICE_QNAME, features);
    }

    public DocumentConverterService_Service(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTCONVERTERSERVICE_QNAME);
    }

    public DocumentConverterService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTCONVERTERSERVICE_QNAME, features);
    }

    public DocumentConverterService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentConverterService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentConverterService
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentConverterService")
    public DocumentConverterService getBasicHttpBindingDocumentConverterService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_DocumentConverterService"), DocumentConverterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentConverterService
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentConverterService")
    public DocumentConverterService getBasicHttpBindingDocumentConverterService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_DocumentConverterService"), DocumentConverterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTCONVERTERSERVICE_EXCEPTION!= null) {
            throw DOCUMENTCONVERTERSERVICE_EXCEPTION;
        }
        return DOCUMENTCONVERTERSERVICE_WSDL_LOCATION;
    }

}
